_init_model: false
context:
- endpoint:hash
dropout: 0.0
ensemble_size: 3
features:
- - clogp
  - transformer://models/llm/lchemme-1:clean_smiles
learning_rate: 1.0e-05
merge_method: product
n_context: 256
n_hidden: 1
n_input:
- 3785
n_out: 1
n_units: 128
optimizer: !!python/name:torch.optim.adam.Adam ''
reduce_lr_on_plateau: true
reduce_lr_patience: 10
residual_depth: 2
